name: Deploy to Hetzner

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Dar permissão de execução ao gradlew
        run: chmod +x ./gradlew
      - name: Build JAR com Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build -t blink-be .

      - name: Exportar Docker image
        run: docker save blink-be | gzip > blink-be.tar.gz

      - name: Enviar imagem para Hetzner
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "blink-be.tar.gz"
          target: "/opt/backend/dev/"

      - name: Executar container no Hetzner
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load < /opt/backend/dev/blink-be.tar.gz
            docker stop blink-be-dev || true
            docker rm blink-be-dev || true
            docker run -d --name blink-be-dev \
            -p 3003:3003 \
            -e SPRING_PROFILES_ACTIVE=dev
            --network blink-docker-network \
            --env-file /opt/backend/dev/.env blink-be
